server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}/personal-financial-control?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    org:
      hibernate:
        envers:
          store_data_at_delete: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            auth-server-url: ${KEYCLOAK_URL}
            realm: personal-financial-control-realm
            client-id: personal-financial-control-client-admin
            client-secret: ${KEYCLOAK_CLIENT_ADMIN_SECRET}
            authorization-grant-type: password
            scope: openid, profile, email
            client-name: Personal Financial Control Admin
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/personal-financial-control-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/personal-financial-control-realm
          jwk-set-uri: ${KEYCLOAK_URL}/realms/personal-financial-control-realm/protocol/openid-connect/certs
