version: '3.8'

services:
  personal-financial-control-db:
    image: mysql:latest
    container_name: personal-financial-control-db
    environment:
      MYSQL_DATABASE: personal-financial-control
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
    volumes:
      - /home/sergioluigi/repositorios/pessoal/volumes/personal-financial-control:/var/lib/mysql
    ports:
      - "3306:3306"
  keycloack-mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/sergioluigi/repositorios/pessoal/volumes/keycloack-mysql-db:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    restart: always
    command:
      - start-dev
      - --http-port=7080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloack-mysql-db/keycloak?useSSL=false&allowPublicKeyRetrieval=true
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HTTP_ENABLED: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    ports:
      - "7080:7080"
      - "8083:8083"
    depends_on:
      - keycloack-mysql-db
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
